# Usamos una versión ligera de Python
FROM python:3.12-slim  

# Establece el directorio de trabajo
WORKDIR /app 

# Copia el archivo de requisitos para instalar las dependencias primero (aprovechando la caché de Docker)
COPY requirements.txt .

# Instala las dependencias sin guardar caché del gestor pip para mantener ligera la imagen
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

# Inicia el servidor
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]