# Imagen base (Necesitamos un sistema operativo base para ejecutar el código)
FROM alpine:latest

# Variable de Entorno (Le damos un valor por defecto a nuestro nombre)
ENV NAME="Izan"

# Comando (Lo que queremos que haga al arrancar)
CMD ["sh", "-c", "echo Hello, $NAME"]
# Ejecutamos este comando al iniciar el contenedor
# CMD ["echo", "Hola Capitán"]